# Generated by Django 5.0.7 on 2026-08-13 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount_cents', models.BigIntegerField()),
                ('term_months', models.PositiveSmallIntegerField()),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('monthly_income_cents', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('approved_interest_rate_bps', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('annual_interest_rate_bps', models.PositiveIntegerField(help_text='Basis points, e.g. 950 = 9.50%')),
                ('min_amount_cents', models.BigIntegerField()),
                ('max_amount_cents', models.BigIntegerField()),
                ('min_term_months', models.PositiveSmallIntegerField()),
                ('max_term_months', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('late', 'Late'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
    ]
