# Generated by Django 5.0.7 on 2026-08-13 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=17, unique=True)),
                ('routing_number', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20)),
                ('provider_account_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_card_id', models.CharField(max_length=120)),
                ('last4', models.CharField(max_length=4)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='posted', max_length=20)),
                ('source_type', models.CharField(choices=[('transfer', 'Internal transfer'), ('deposit', 'Deposit (Stripe)'), ('withdrawal', 'Withdrawal (Stripe)'), ('loan_disbursement', 'Loan disbursement'), ('loan_repayment', 'Loan repayment'), ('manual_adjustment', 'Manual adjustment'), ('interest', 'Interest')], max_length=30)),
                ('source_id', models.UUIDField()),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending second approval'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='pending_approval', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('destination_account_number', models.CharField(max_length=17)),
                ('destination_routing_number', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('stripe_payout_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
