# Generated by Django 5.0.7 on 2026-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='block_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
