# Generated by Django 5.0.7 on 2026-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_card_block_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending activation'), ('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
