# Generated by Django 5.0.7 on 2026-08-16 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_card_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('verve', 'Verve')], max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='card',
            name='provider_card_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('active', 'Active'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
