# Generated by Django 5.0.7 on 2026-08-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_card_card_type_card_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualadjustment',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
