# Generated by Django 5.0.7 on 2026-08-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_pendingtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransfer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='destination_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='swift_bic',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='transfer_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=20),
        ),
        migrations.AddField(
            model_name='transfer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='transfer',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transfer',
            name='swift_bic',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingtransfer',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='banking.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='banking.account'),
        ),
    ]
