# Generated by Django 5.0.7 on 2026-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('security', 'Security'), ('transaction', 'Transaction'), ('loan', 'Loan'), ('card', 'Card'), ('kyc', 'KYC'), ('system', 'System')], max_length=20),
        ),
    ]
