# Generated by Django 5.0.7 on 2026-08-17 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('all', 'All customers'), ('specific', 'Specific users')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_notices', to=settings.AUTH_USER_MODEL),
        ),
    ]
